### ISSUE TITLE
Don't require java.system.class.loader

### ISSUE THREAD

**Issue by gravit0** [GTNewHorizons/RetroFuturaBootstrap#3]
We use our own ClassLoader and do some work before running Minecraft. Our ClassLoader supports the ability to transform classes, getURLs, addURL, defineClass, supports the use of Java 9+ modules (however, classes in modules cannot be transformed) and more.
The lwjgl3ify 2.0.0 update forces the use of RetroFuturaBootstrap, which requires the java.system.class.loader property to be set, which is not possible. It is worth considering the possibility of changing the code so that setting this property is not required
We are not able to implement any interfaces in ClassLoader, since it is used not only on 1.7.10. However, we can provide an accessor object that implements the necessary functions, but is not a descendant of ClassLoader

**Comment by eigenraven** [comment]
I have added a way you can achieve this:
 - In your class loader, before main, set the `rfb.skipClassLoaderCheck` System property to "true"
 - Set RfbSystemClassLoader.addURLHook to an implementation that adds URLs to the system loader
I don't think I'll ever fully support this configuration, but I'll try to not break it if possible.
